### ISSUE TITLE
Assertion error when linked with intel-compute-runtime

### ISSUE THREAD

**Issue by mat813** [not-an-aardvark/lucky-commit#26]
Using Arch Linux, today, lucky_commit fails, I was using the arch package, cargo installed it, and it fails all the same:

```
~/.cargo/bin/lucky_commit 0000000                                      
/usr/include/c++/12.2.0/bits/stl_vector.h:1142: std::vector<_Tp, _Alloc>::const_reference std::vector<_Tp, _Alloc>::operator[](size_type) const [with _Tp = NEO::ArgTypeMetadataExtended; _Alloc = std::allocator<NEO::ArgTypeMetadataExtended>; const_reference = const NEO::ArgTypeMetadataExtended&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
[1]    92025 IOT instruction (core dumped)  ~/.cargo/bin/lucky_commit 0000000
```

This is using an intel graphics card with intel-compute-runtime installed.

If I remove intel-compute-runtime, it works, but, well, it is slooowww :disappointed:

**Comment by not-an-aardvark** [comment]
This error seems like it's coming from an out-of-bounds read [inside intel-compute-runtime](https://github.com/intel/compute-runtime/blob/2ed2ac73d12f3d94fe862acfd31ea6adfaff07ec/shared/source/kernel/kernel_descriptor.h#L180). I'm not sure I'll be able to help much with this given the info provided, since I don't have access to that GPU/OS setup and this seems to work fine on other systems.

If you're interested in debugging yourself, it could be interesting to get a stacktrace by throwing gdb at it or something, or doing some analysis of the coredump.

**Comment by mat813** [comment]
It does :

```
Thread 1 "lucky_commit" received signal SIGABRT, Aborted.
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
44	     return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff7cdd6b3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff7c8d938 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff7c7753d in __GI_abort () at abort.c:79
#4  0x00007ffff6b340a2 in std::__glibcxx_assert_fail (file=<optimized out>, line=<optimized out>, function=<optimized out>, condition=<optimized out>) at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/debug.cc:60
#5  0x00007ffff6e86d2b in ?? () from /usr/lib/intel-opencl/libigdrcl.so
#6  0x00007ffff6e2bcd8 in ?? () from /usr/lib/intel-opencl/libigdrcl.so
#7  0x00007ffff7f5a2fe in clGetKernelArgInfo () from /usr/lib/libOpenCL.so.1
#8  0x00005555556b1a6c in ocl_core::functions::get_kernel_arg_info (obj=0x7fffffff69a8, arg_index=0, request=ocl_core::KernelArgInfo::TypeName, device_versions=...)
    at /home/mat/.cargo/registry/src/github.com-1ecc6299db9ec823/ocl-core-0.11.2/src/functions.rs:2197
#9  0x0000555555625154 in ocl::standard::kernel::arg_info (core=0x7fffffff69a8, arg_idx=0, info_kind=ocl_core::KernelArgInfo::TypeName)
    at /home/mat/.cargo/registry/src/github.com-1ecc6299db9ec823/ocl-0.19.3/src/standard/kernel.rs:1499
#10 0x000055555562520c in ocl::standard::kernel::arg_type_name (core=0x7fffffff69a8, arg_idx=0) at /home/mat/.cargo/registry/src/github.com-1ecc6299db9ec823/ocl-0.19.3/src/standard/kernel.rs:1505
#11 0x00005555556284bb in ocl::standard::kernel::arg_type::ArgType::from_kern_and_idx (core=0x7fffffff69a8, arg_idx=0)
    at /home/mat/.cargo/registry/src/github.com-1ecc6299db9ec823/ocl-0.19.3/src/standard/kernel.rs:1665
#12 0x0000555555624046 in ocl::standard::kernel::KernelBuilder::build (self=0x7fffffff90f8) at /home/mat/.cargo/registry/src/github.com-1ecc6299db9ec823/ocl-0.19.3/src/standard/kernel.rs:1432
#13 0x00005555555c7317 in lucky_commit::HashSearchWorker<lucky_commit::Sha1>::search_with_gpu<lucky_commit::Sha1> (self=...)
    at /home/mat/.cargo/registry/src/github.com-1ecc6299db9ec823/lucky_commit-2.2.1/src/lib.rs:403
#14 0x00005555555cded5 in lucky_commit::HashSearchWorker<lucky_commit::Sha1>::search<lucky_commit::Sha1> (self=...) at /home/mat/.cargo/registry/src/github.com-1ecc6299db9ec823/lucky_commit-2.2.1/src/lib.rs:283
#15 0x000055555557d373 in lucky_commit::run_lucky_commit<lucky_commit::Sha1> (existing_commit=..., maybe_prefix=...) at /home/mat/.cargo/registry/src/github.com-1ecc6299db9ec823/lucky_commit-2.2.1/src/bin.rs:49
#16 0x000055555557d184 in lucky_commit::main () at /home/mat/.cargo/registry/src/github.com-1ecc6299db9ec823/lucky_commit-2.2.1/src/bin.rs:36
```

**Comment by mat813** [comment]
An update of the intel-compute-runtime package fixed this.
