### ISSUE TITLE
error on build

### ISSUE THREAD

**Issue by KnowsCount** [not-an-aardvark/lucky-commit#8]
```
➜  lucky-commit git:(C) make                       
gcc -Wall -std=c99 -pedantic -O3 -DNDEBUG -flto -pthread -o lucky-commit lucky-commit.c -I/usr/local/opt/openssl/include/ -lcrypto -lm -lz
lucky-commit.c: In function ‘luckyCommit’:
lucky-commit.c:386:15: error: assignment of read-only location ‘params[i]’
  386 |     params[i] = (struct HashSearchParams){
      |               ^
make: *** [Makefile:2: default] Error 1
```

I do not understand C and therefore do not under stand this.... the rust version does not function on my vps too... it was because of some `linking with cc failed: exit status: 1` issue...

as for the node.js version, it says something like this:

```
➜  lucky-commit git:(C) lucky-commit 0123456
BUG: gpg-interface.c:234: bad signature '                                                                                                                                        -----BEGIN PGP SIGNATURE-----

iQIzBAABCAAdFiEEAi0gbOrlm631M8iWt57Hq8CqU6AFAlomDUkACgkQt57Hq8Cq
U6Du9xAAhCmBTFC4YhgxMveYFHXII5pPNGbRQjjdNTVQMfDQdNoBnIoZ8/KlCNnU
Vj6UrXLsrtm76yKB0JTfMRtDxv8QPsdc+fjIh0ctiSOm710sHxcB3OVtnP+RJpsd
gTwkzkb21zjM5S2ZnSz5vSzfa1x36APt2QiZSv4ObaY/cg/ypnC2vNEmzhmASqns
buHLNlP72CBFlHDIpGk7TDLELAcQDAMq1tnkQfVMbgsfYdATzpHDo4AUrUBD/L1H
AQ/wT62qu1abq7Xyyh3nSZt+N2gGkt8DiBe52syhSVhx8otdur9aH6veUXS8wQmJ
8N8J9ygHJ8RAIfXwg9iIKHFyQp2o+8BDpWdUldlohZfWMxuOAJ8i3y7l9oQi9nZY
ehkaCfwSUoE/pLynLjap3tpcthB457gPoCgkDjkTLeGJD7vRlA8L0dW1DU1y4QFe
dGefaHFjPxzRjH4MZna4nQDK7b4b6MN0hcMvzSDNeS9iGhRMzk9miFlFzMAdVPA+
ChL3p0wWd+TG22W4kPwm9qbweZOuwM12y2vKm2svfBwkQ0/cHDwWY8d+moPLGTpa
hz8h3pQGXOSAw3lEK/JB39aG/u6SrCkhwgAUzHUQGb6Oh8ldlUFuC37DH5hM2VMp
ejB2xBvU3F9LBjQIHyqEYHpOq9fw46jEsxDAqHU34kTHJY1PSzI=
=Zoo4
-----END PGP SIGNATURE-----
'
child_process.js:682
    throw err;
    ^

Error: Command failed: git --no-pager show -s --oneline --format="%GG" HEAD
BUG: gpg-interface.c:234: bad signature '                                                                                                                                        -----BEGIN PGP SIGNATURE-----

iQIzBAABCAAdFiEEAi0gbOrlm631M8iWt57Hq8CqU6AFAlomDUkACgkQt57Hq8Cq
U6Du9xAAhCmBTFC4YhgxMveYFHXII5pPNGbRQjjdNTVQMfDQdNoBnIoZ8/KlCNnU
Vj6UrXLsrtm76yKB0JTfMRtDxv8QPsdc+fjIh0ctiSOm710sHxcB3OVtnP+RJpsd
gTwkzkb21zjM5S2ZnSz5vSzfa1x36APt2QiZSv4ObaY/cg/ypnC2vNEmzhmASqns
buHLNlP72CBFlHDIpGk7TDLELAcQDAMq1tnkQfVMbgsfYdATzpHDo4AUrUBD/L1H
AQ/wT62qu1abq7Xyyh3nSZt+N2gGkt8DiBe52syhSVhx8otdur9aH6veUXS8wQmJ
8N8J9ygHJ8RAIfXwg9iIKHFyQp2o+8BDpWdUldlohZfWMxuOAJ8i3y7l9oQi9nZY
ehkaCfwSUoE/pLynLjap3tpcthB457gPoCgkDjkTLeGJD7vRlA8L0dW1DU1y4QFe
dGefaHFjPxzRjH4MZna4nQDK7b4b6MN0hcMvzSDNeS9iGhRMzk9miFlFzMAdVPA+
ChL3p0wWd+TG22W4kPwm9qbweZOuwM12y2vKm2svfBwkQ0/cHDwWY8d+moPLGTpa
hz8h3pQGXOSAw3lEK/JB39aG/u6SrCkhwgAUzHUQGb6Oh8ldlUFuC37DH5hM2VMp
ejB2xBvU3F9LBjQIHyqEYHpOq9fw46jEsxDAqHU34kTHJY1PSzI=
=Zoo4
-----END PGP SIGNATURE-----
'

    at checkExecSyncError (child_process.js:643:11)
    at Object.execSync (child_process.js:679:15)
    at exec (/usr/lib/node_modules/lucky-commit/index.js:5:35)
    at luckyCommit (/usr/lib/node_modules/lucky-commit/index.js:25:7)
    at Object.<anonymous> (/usr/lib/node_modules/lucky-commit/index.js:40:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  status: null,
  signal: 'SIGABRT',
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(940) [Uint8Array] [
       66,  85,  71, 58,  32, 103, 112, 103,  45, 105, 110, 116,
      101, 114, 102, 97,  99, 101,  46,  99,  58,  50,  51,  52,
       58,  32,  98, 97, 100,  32, 115, 105, 103, 110,  97, 116,
      117, 114, 101, 32,  39,  32,   9,  32,  32,   9,   9,  32,
        9,   9,  32, 32,  32,  32,   9,   9,   9,  32,   9,   9,
       32,  32,   9,  9,  32,  32,  32,  32,  32,  32,  32,  32,
       32,  32,  32, 32,  32,  32,  32,  32,  32,  32,  32,  32,
       32,  32,  32, 32,  32,  32,  32,  32,  32,  32,  32,  32,
       32,  32,  32, 32,
      ... 840 more items
    ]
  ],
  pid: 26865,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(940) [Uint8Array] [
     66,  85,  71, 58,  32, 103, 112, 103,  45, 105, 110, 116,
    101, 114, 102, 97,  99, 101,  46,  99,  58,  50,  51,  52,
     58,  32,  98, 97, 100,  32, 115, 105, 103, 110,  97, 116,
    117, 114, 101, 32,  39,  32,   9,  32,  32,   9,   9,  32,
      9,   9,  32, 32,  32,  32,   9,   9,   9,  32,   9,   9,
     32,  32,   9,  9,  32,  32,  32,  32,  32,  32,  32,  32,
     32,  32,  32, 32,  32,  32,  32,  32,  32,  32,  32,  32,
     32,  32,  32, 32,  32,  32,  32,  32,  32,  32,  32,  32,
     32,  32,  32, 32,
    ... 840 more items
  ]
}
```

**Comment by not-an-aardvark** [comment]
The C and Node.js versions of the tool are unmaintained, but I might be able to help with compiling the Rust version if you can provide more details about the error (ideally the entire command you're using to try to compile the rust version, as well as the entire output of the command).

**Comment by KnowsCount** [comment]
sorry, this response is a bit late but do give me sometime... I planned to provide the information tomorrow night, because I've been very busy finishing my school year up lately. please reopen this issue for now. sorry, sorry, sorry.

**Comment by KnowsCount** [comment]
my rust version is `1.53.0`:

```
➜  lucky-commit git:(main) cargo -V
cargo 1.53.0 (4369396ce 2021-04-27)
```

I am on ubuntu and it is versioned `20.04.2`:

```
➜  lucky-commit git:(main) cat /etc/issue
Ubuntu 20.04.2 LTS \n \l
```

this is the output when I run `cargo install lucky_commit --locked`: 

```
➜  lucky-commit git:(main) ls
build.rs  Cargo.lock  Cargo.toml  LICENSE.md  README.md  src
➜  lucky-commit git:(main) cargo install lucky_commit --locked
    Updating crates.io index
  Installing lucky_commit v2.0.3
   Compiling autocfg v1.0.1
   Compiling libc v0.2.94
   Compiling maybe-uninit v2.0.0
   Compiling cc v1.0.67
   Compiling proc-macro2 v1.0.26
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.72
   Compiling semver v0.1.20
   Compiling cl-sys v0.4.2
   Compiling failure_derive v0.1.8
   Compiling lazy_static v1.4.0
   Compiling cfg-if v0.1.10
   Compiling bitflags v1.2.1
   Compiling rustc-serialize v0.3.24
   Compiling gimli v0.24.0
   Compiling scopeguard v1.1.0
   Compiling adler v1.0.2
   Compiling typenum v1.13.0
   Compiling object v0.24.0
   Compiling version_check v0.9.3
   Compiling rustc-demangle v0.1.19
   Compiling cfg-if v1.0.0
   Compiling futures v0.1.31
   Compiling nodrop v0.1.14
   Compiling opaque-debug v0.3.0
   Compiling cpufeatures v0.1.3
   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling crossbeam-utils v0.7.2
   Compiling memoffset v0.5.6
   Compiling miniz_oxide v0.4.4
   Compiling crossbeam-epoch v0.8.2
   Compiling num-iter v0.1.42
   Compiling rustc_version v0.1.7
   Compiling backtrace v0.3.59
   Compiling sha1-asm v0.4.4
   Compiling addr2line v0.15.1
   Compiling generic-array v0.14.4
   Compiling ocl-core v0.11.2
   Compiling rand v0.4.6
   Compiling num_cpus v1.13.0
   Compiling quote v1.0.9
   Compiling num-complex v0.1.43
   Compiling num-traits v0.1.43
   Compiling crossbeam-queue v0.2.3
   Compiling crossbeam-channel v0.4.4
   Compiling num-bigint v0.1.44
   Compiling block-buffer v0.9.0
   Compiling digest v0.9.0
   Compiling enum_primitive v0.1.1
   Compiling crossbeam-deque v0.7.3
   Compiling num-rational v0.1.42
   Compiling sha-1 v0.9.6
   Compiling crossbeam v0.7.3
   Compiling synstructure v0.12.4
   Compiling num v0.1.42
   Compiling qutex v0.2.3
   Compiling ocl-core-vector v0.1.0
   Compiling failure v0.1.8
   Compiling ocl v0.19.3
   Compiling lucky_commit v2.0.3
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-Wl,--as-needed" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/tmp/cargo-installlpKv7F/release/build/lucky_commit-3a80f631e28bf5b0/build_script_build-3a80f631e28bf5b0.build_script_build.cz35sjee-cgu.0.rcgu.o" "/tmp/cargo-installlpKv7F/release/build/lucky_commit-3a80f631e28bf5b0/build_script_build-3a80f631e28bf5b0.build_script_build.cz35sjee-cgu.1.rcgu.o" "/tmp/cargo-installlpKv7F/release/build/lucky_commit-3a80f631e28bf5b0/build_script_build-3a80f631e28bf5b0.build_script_build.cz35sjee-cgu.10.rcgu.o" "/tmp/cargo-installlpKv7F/release/build/lucky_commit-3a80f631e28bf5b0/build_script_build-3a80f631e28bf5b0.build_script_build.cz35sjee-cgu.11.rcgu.o" "/tmp/cargo-installlpKv7F/release/build/lucky_commit-3a80f631e28bf5b0/build_script_build-3a80f631e28bf5b0.build_script_build.cz35sjee-cgu.12.rcgu.o" "/tmp/cargo-installlpKv7F/release/build/lucky_commit-3a80f631e28bf5b0/build_script_build-3a80f631e28bf5b0.build_script_build.cz35sjee-cgu.13.rcgu.o" "/tmp/cargo-installlpKv7F/release/build/lucky_commit-3a80f631e28bf5b0/build_script_build-3a80f631e28bf5b0.build_script_build.cz35sjee-cgu.14.rcgu.o" "/tmp/cargo-installlpKv7F/release/build/lucky_commit-3a80f631e28bf5b0/build_script_build-3a80f631e28bf5b0.build_script_build.cz35sjee-cgu.15.rcgu.o" "/tmp/cargo-installlpKv7F/release/build/lucky_commit-3a80f631e28bf5b0/build_script_build-3a80f631e28bf5b0.build_script_build.cz35sjee-cgu.2.rcgu.o" "/tmp/cargo-installlpKv7F/release/build/lucky_commit-3a80f631e28bf5b0/build_script_build-3a80f631e28bf5b0.build_script_build.cz35sjee-cgu.3.rcgu.o" "/tmp/cargo-installlpKv7F/release/build/lucky_commit-3a80f631e28bf5b0/build_script_build-3a80f631e28bf5b0.build_script_build.cz35sjee-cgu.4.rcgu.o" "/tmp/cargo-installlpKv7F/release/build/lucky_commit-3a80f631e28bf5b0/build_script_build-3a80f631e28bf5b0.build_script_build.cz35sjee-cgu.5.rcgu.o" "/tmp/cargo-installlpKv7F/release/build/lucky_commit-3a80f631e28bf5b0/build_script_build-3a80f631e28bf5b0.build_script_build.cz35sjee-cgu.6.rcgu.o" "/tmp/cargo-installlpKv7F/release/build/lucky_commit-3a80f631e28bf5b0/build_script_build-3a80f631e28bf5b0.build_script_build.cz35sjee-cgu.7.rcgu.o" "/tmp/cargo-installlpKv7F/release/build/lucky_commit-3a80f631e28bf5b0/build_script_build-3a80f631e28bf5b0.build_script_build.cz35sjee-cgu.8.rcgu.o" "/tmp/cargo-installlpKv7F/release/build/lucky_commit-3a80f631e28bf5b0/build_script_build-3a80f631e28bf5b0.build_script_build.cz35sjee-cgu.9.rcgu.o" "-o" "/tmp/cargo-installlpKv7F/release/build/lucky_commit-3a80f631e28bf5b0/build_script_build-3a80f631e28bf5b0" "/tmp/cargo-installlpKv7F/release/build/lucky_commit-3a80f631e28bf5b0/build_script_build-3a80f631e28bf5b0.42sbljg9gktz7wmk.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "/tmp/cargo-installlpKv7F/release/deps" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/cargo-installlpKv7F/release/deps/libocl-a49ee9f3c3166e75.rlib" "/tmp/cargo-installlpKv7F/release/deps/libqutex-58abdf0e792bb1ee.rlib" "/tmp/cargo-installlpKv7F/release/deps/libcrossbeam-03de80bec44a516d.rlib" "/tmp/cargo-installlpKv7F/release/deps/libcrossbeam_queue-f2f8581191758240.rlib" "/tmp/cargo-installlpKv7F/release/deps/libcrossbeam_channel-341a9d2c6a7d01e1.rlib" "/tmp/cargo-installlpKv7F/release/deps/libcrossbeam_deque-758217a17ffb12dc.rlib" "/tmp/cargo-installlpKv7F/release/deps/libcrossbeam_epoch-93270a7465036342.rlib" "/tmp/cargo-installlpKv7F/release/deps/libscopeguard-8fd589f05c959cf5.rlib" "/tmp/cargo-installlpKv7F/release/deps/libmemoffset-600c27b669e92e90.rlib" "/tmp/cargo-installlpKv7F/release/deps/libcrossbeam_utils-0b16235ac5ba430f.rlib" "/tmp/cargo-installlpKv7F/release/deps/liblazy_static-d5f289da30f1986f.rlib" "/tmp/cargo-installlpKv7F/release/deps/libmaybe_uninit-4e3184c82b9ce559.rlib" "/tmp/cargo-installlpKv7F/release/deps/libcfg_if-808413b6155e99e0.rlib" "/tmp/cargo-installlpKv7F/release/deps/libnodrop-c0575061c494e770.rlib" "/tmp/cargo-installlpKv7F/release/deps/libocl_core-7fe6d18442bcb64f.rlib" "/tmp/cargo-installlpKv7F/release/deps/libcl_sys-872c6ae326341762.rlib" "/tmp/cargo-installlpKv7F/release/deps/libocl_core_vector-a13b3c3bfe11d396.rlib" "/tmp/cargo-installlpKv7F/release/deps/libnum-6b579db0a7989c75.rlib" "/tmp/cargo-installlpKv7F/release/deps/libnum_rational-86df2ef6483ca107.rlib" "/tmp/cargo-installlpKv7F/release/deps/libnum_bigint-1751741a713dc676.rlib" "/tmp/cargo-installlpKv7F/release/deps/librand-64b6b7f061d92c63.rlib" "/tmp/cargo-installlpKv7F/release/deps/libnum_iter-747032977aa24979.rlib" "/tmp/cargo-installlpKv7F/release/deps/libnum_integer-42f861cb2d014209.rlib" "/tmp/cargo-installlpKv7F/release/deps/libnum_complex-063afd17cd7dd5dc.rlib" "/tmp/cargo-installlpKv7F/release/deps/librustc_serialize-191430b3c3d3083a.rlib" "/tmp/cargo-installlpKv7F/release/deps/libenum_primitive-23197397c7c053a6.rlib" "/tmp/cargo-installlpKv7F/release/deps/libnum_traits-f65cb2d7f576c18d.rlib" "/tmp/cargo-installlpKv7F/release/deps/libbitflags-01914ed2c682265b.rlib" "/tmp/cargo-installlpKv7F/release/deps/libfailure-0e4bf47778629bd0.rlib" "/tmp/cargo-installlpKv7F/release/deps/libbacktrace-fe53bd7d66f774fb.rlib" "/tmp/cargo-installlpKv7F/release/deps/libminiz_oxide-c5db77280e103858.rlib" "/tmp/cargo-installlpKv7F/release/deps/libadler-ba099086ca4983a8.rlib" "/tmp/cargo-installlpKv7F/release/deps/libobject-135eab7a1b95c635.rlib" "/tmp/cargo-installlpKv7F/release/deps/liblibc-3ff3da2867f3be25.rlib" "/tmp/cargo-installlpKv7F/release/deps/libaddr2line-c2695fc818f63024.rlib" "/tmp/cargo-installlpKv7F/release/deps/libgimli-14d8ccd75a214490.rlib" "/tmp/cargo-installlpKv7F/release/deps/libcfg_if-3f2ff5586cd18bf7.rlib" "/tmp/cargo-installlpKv7F/release/deps/librustc_demangle-5a3744bccdb4b419.rlib" "/tmp/cargo-installlpKv7F/release/deps/libfutures-a15d6e5c744bc546.rlib" "/tmp/cargo-installlpKv7F/release/deps/libnum_traits-ae3863a5755821fa.rlib" "-Wl,--start-group" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-b6b48477bfa8c673.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-f560ec02638f7ffe.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-9c8eadb7013c9e0b.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-8b0ec8dbdb85d0bf.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-ba5d5ee707c805d2.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-55166126dbdd5e46.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-c327b365eae3b2f3.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-416439b546a0d033.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-2581188d29552e15.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-da7b2635bfcce6ef.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-09200ed1945e7b2b.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-223ac369b29f5000.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-39562fe6600dd936.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-9b411bb7a19f81b3.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-64ea0581d80339f7.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-b2dbda88b377d685.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-2a8415a96ed1d7dc.rlib" "-Wl,--end-group" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-c4d9a5b072ee3191.rlib" "-Wl,-Bdynamic" "-lOpenCL" "-lOpenCL" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc"
  = note: /usr/bin/ld: cannot find -lOpenCL
          /usr/bin/ld: cannot find -lOpenCL
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: could not compile `lucky_commit`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `lucky_commit v2.0.3`, intermediate artifacts can be found at `/tmp/cargo-installlpKv7F`

Caused by:
  build failed
```

the same thing appears when I am trying to build with source, too (by running `cargo build --release`).

It seems like the error is `linking with `cc` failed`, and after a bit of searching on stackoverflow, I found some solutions but none of those seemed to work...

**Comment by not-an-aardvark** [comment]
It looks like the issue is that you don't have OpenCL headers:

```
  = note: /usr/bin/ld: cannot find -lOpenCL
          /usr/bin/ld: cannot find -lOpenCL
          collect2: error: ld returned 1 exit status
```

As a quick fix, you could use `cargo install lucky_commit --locked --no-default-features`. This will make `lucky_commit` run on CPUs rather than a GPU, which will work but will typically be a bit slower, on the order of ~15ish seconds depending on your hardware.

It might also be possible to set up the GPU version somehow, but I'm not sure how (I don't have a lot of background on how to set up OpenCL on various operating systems). My understanding is that there's a package you can install to get the OpenCL headers, but I don't know if there are additional steps needed beyond that. If you end up figuring it out, I'd be happy to accept a pull request to add more details about this to the readme.

**Comment by KnowsCount** [comment]
with the `--no-default-features` flag, the installation seemed to work, thanks!

I'd be more than happy to contribute to this repository, the research is already under process.
