### ISSUE TITLE
Error on cargo build

### ISSUE THREAD

**Issue by hunter-horton** [not-an-aardvark/lucky-commit#9]
When trying to install from cargo with the command in the readme
`cargo install lucky_commit --locked`
An error is thrown due to the assertion on line 27 of build.rs. It looks like you are requiring 1 OpenCL binary, but in my case there are two. See full backtrace:
```  Installing lucky_commit v2.0.3
   Compiling autocfg v1.0.1
   Compiling libc v0.2.94
   Compiling maybe-uninit v2.0.0
   Compiling cc v1.0.67
   Compiling proc-macro2 v1.0.26
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.72
   Compiling cl-sys v0.4.2
   Compiling lazy_static v1.4.0
   Compiling bitflags v1.2.1
   Compiling semver v0.1.20
   Compiling cfg-if v0.1.10
   Compiling failure_derive v0.1.8
   Compiling rustc-serialize v0.3.24
   Compiling gimli v0.24.0
   Compiling scopeguard v1.1.0
   Compiling adler v1.0.2
   Compiling object v0.24.0
   Compiling version_check v0.9.3
   Compiling rustc-demangle v0.1.19
   Compiling typenum v1.13.0
   Compiling cfg-if v1.0.0
   Compiling futures v0.1.31
   Compiling nodrop v0.1.14
   Compiling opaque-debug v0.3.0
   Compiling cpufeatures v0.1.3
   Compiling rustc_version v0.1.7
   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling crossbeam-utils v0.7.2
   Compiling memoffset v0.5.6
   Compiling crossbeam-epoch v0.8.2
   Compiling num-iter v0.1.42
   Compiling miniz_oxide v0.4.4
   Compiling generic-array v0.14.4
   Compiling backtrace v0.3.59
   Compiling sha1-asm v0.4.4
   Compiling ocl-core v0.11.2
   Compiling rand v0.4.6
   Compiling num_cpus v1.13.0
   Compiling quote v1.0.9
   Compiling addr2line v0.15.1
   Compiling crossbeam-queue v0.2.3
   Compiling crossbeam-channel v0.4.4
   Compiling crossbeam-deque v0.7.3
   Compiling block-buffer v0.9.0
   Compiling digest v0.9.0
   Compiling num-complex v0.1.43
   Compiling num-traits v0.1.43
   Compiling sha-1 v0.9.6
   Compiling crossbeam v0.7.3
   Compiling enum_primitive v0.1.1
   Compiling num-bigint v0.1.44
   Compiling qutex v0.2.3
   Compiling num-rational v0.1.42
   Compiling num v0.1.42
   Compiling ocl-core-vector v0.1.0
   Compiling synstructure v0.12.4
   Compiling failure v0.1.8
   Compiling ocl v0.19.3
   Compiling lucky_commit v2.0.3
error: failed to compile `lucky_commit v2.0.3`, intermediate artifacts can be found at `/var/folders/cs/v420p4ps4bsf3w3f5cnwv1p40000gq/T/cargo-installlyiZ2x`

Caused by:
  failed to run custom build command for `lucky_commit v2.0.3`

Caused by:
  process didn't exit successfully: `/var/folders/cs/v420p4ps4bsf3w3f5cnwv1p40000gq/T/cargo-installlyiZ2x/release/build/lucky_commit-168d6b20729190ad/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs

  --- stderr
  thread 'main' panicked at 'assertion failed: `(left == right)`
    left: `2`,
   right: `1`', /Users/hunterhorton/.cargo/registry/src/github.com-1ecc6299db9ec823/lucky_commit-2.0.3/build.rs:27:9
  stack backtrace:
     0:        0x1045b9ba4 - std::backtrace_rs::backtrace::libunwind::trace::h67b1783e93f517c7
                                 at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
     1:        0x1045b9ba4 - std::backtrace_rs::backtrace::trace_unsynchronized::h6642b95f229b3f12
                                 at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:        0x1045b9ba4 - std::sys_common::backtrace::_print_fmt::h0a233062426578e9
                                 at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:67:5
     3:        0x1045b9ba4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5b5b7de1c79b4b45
                                 at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:46:22
     4:        0x1045d0ace - core::fmt::write::h65ec8c8a6aa7b549
                                 at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/fmt/mod.rs:1094:17
     5:        0x1045b7f0a - std::io::Write::write_fmt::hc52e560ab9e57db4
                                 at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/io/mod.rs:1584:15
     6:        0x1045bb7cf - std::sys_common::backtrace::_print::h27e4664250aa8eaf
                                 at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:49:5
     7:        0x1045bb7cf - std::sys_common::backtrace::print::hb149f667a3c579ca
                                 at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:36:9
     8:        0x1045bb7cf - std::panicking::default_hook::{{closure}}::h0974624c30a6e2b5
                                 at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:208:50
     9:        0x1045bb2d9 - std::panicking::default_hook::hda3cfa32e0773aac
                                 at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:225:9
    10:        0x1045bbe35 - std::panicking::rust_panic_with_hook::h1cdaa4b48d8ea4a1
                                 at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:591:17
    11:        0x1045bb975 - std::panicking::begin_panic_handler::{{closure}}::h51157b4dbc4c5d91
                                 at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:497:13
    12:        0x1045ba038 - std::sys_common::backtrace::__rust_end_short_backtrace::h8f7fee8b4c5a0c05
                                 at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:141:18
    13:        0x1045bb8da - rust_begin_unwind
                                 at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
    14:        0x1045d810f - core::panicking::panic_fmt::h28a37220b8fae52a
                                 at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
    15:        0x1045cfcea - core::panicking::assert_failed::inner::h4054bb848a89e408
                                 at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:135:21
    16:        0x1045d5604 - core::panicking::assert_failed::he03d2f44c135bdb3
    17:        0x10453bdd4 - build_script_build::precompile_opencl::hd0e98455fb29ef4a
    18:        0x10453bb47 - build_script_build::main::hf59ae1878853f294
    19:        0x10453ad3a - core::ops::function::FnOnce::call_once::h9065a3b185aacc6e
    20:        0x10453aead - std::sys_common::backtrace::__rust_begin_short_backtrace::h66e9250d52eb21c5
    21:        0x10453acc0 - std::rt::lang_start::{{closure}}::hce1378d2f0f187cc
    22:        0x1045bc1a1 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hc43f50f6c262e503
                                 at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:259:13
    23:        0x1045bc1a1 - std::panicking::try::do_call::ha2a21b2645967438
                                 at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:379:40
    24:        0x1045bc1a1 - std::panicking::try::h1ca18252e93fb057
                                 at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:343:19
    25:        0x1045bc1a1 - std::panic::catch_unwind::h64441306bfaea78f
                                 at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:431:14
    26:        0x1045bc1a1 - std::rt::lang_start_internal::h37583e1fa93097c4
                                 at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/rt.rs:34:21
    27:        0x10453aca2 - std::rt::lang_start::hc04b22526a462096
    28:        0x10453c136 - _main
```

This might be as easy as just changing the assert to at least 1 instead of exactly 1.

**Comment by not-an-aardvark** [comment]
Thanks for reporting. I think the fix will be a bit more involved than just changing the assert (a couple things need to be updated to handle the possibility of having more than one GPU device), but it shouldn't be extremely difficult as far as I can tell. However, I don't have a machine with multiple GPUs, so I might need help testing the fix.

I think this bug was probably introduced as a result of https://github.com/not-an-aardvark/lucky-commit/commit/0000000ab2ac08bc85c9ec7589b59d8c48009251. As a workaround, you could try installing `v2.0.0` (which didn't include that change) or installing with `--no-default-features` (to run it on CPUs instead).

**Comment by hunter-horton** [comment]
I'm happy to test the fix. I have a macbook pro that has the integrated intel graphics as well as a dedicated AMD chip. In the meantime I'll test your hypothesis about 2.0.1.

**Comment by hunter-horton** [comment]
so after installing v2.0.1 and running 
`time lucky_commit --benchmark`
I am getting the following error. You are correct that installing with `--no-default-features` does work correctly using the CPU implementation.
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Invalid number of devices specified (2). Each 'ProQue' can only be associated with a single device. Use 'Context', 'Program', and 'Queue' separately for multi-device configurations.', /Users/hunterhorton/.cargo/registry/src/github.com-1ecc6299db9ec823/lucky_commit-2.0.1/src/lib.rs:189:43
stack backtrace:
   0:        0x10b94a104 - std::backtrace_rs::backtrace::libunwind::trace::h67b1783e93f517c7
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:        0x10b94a104 - std::backtrace_rs::backtrace::trace_unsynchronized::h6642b95f229b3f12
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10b94a104 - std::sys_common::backtrace::_print_fmt::h0a233062426578e9
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x10b94a104 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5b5b7de1c79b4b45
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x10b964ade - core::fmt::write::h65ec8c8a6aa7b549
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/fmt/mod.rs:1094:17
   5:        0x10b94772a - std::io::Write::write_fmt::hc52e560ab9e57db4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/io/mod.rs:1584:15
   6:        0x10b94bebf - std::sys_common::backtrace::_print::h27e4664250aa8eaf
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x10b94bebf - std::sys_common::backtrace::print::hb149f667a3c579ca
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x10b94bebf - std::panicking::default_hook::{{closure}}::h0974624c30a6e2b5
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:208:50
   9:        0x10b94b9c9 - std::panicking::default_hook::hda3cfa32e0773aac
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:225:9
  10:        0x10b94c525 - std::panicking::rust_panic_with_hook::h1cdaa4b48d8ea4a1
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:591:17
  11:        0x10b94c065 - std::panicking::begin_panic_handler::{{closure}}::h51157b4dbc4c5d91
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:497:13
  12:        0x10b94a598 - std::sys_common::backtrace::__rust_end_short_backtrace::h8f7fee8b4c5a0c05
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:141:18
  13:        0x10b94bfca - rust_begin_unwind
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
  14:        0x10b96e9bf - core::panicking::panic_fmt::h28a37220b8fae52a
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
  15:        0x10b96ea35 - core::result::unwrap_failed::ha7403d21b7149ada
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:1355:5
  16:        0x10b8f68ea - lucky_commit_lib::HashSearchWorker::search::h75bc190e2eb2a347
  17:        0x10b8d4539 - lucky_commit::benchmark::run_benchmark::h8d6bd391cb7a179d
  18:        0x10b8d3098 - lucky_commit::main::h02cf3979533a6326
  19:        0x10b8d284a - std::sys_common::backtrace::__rust_begin_short_backtrace::hce647fe9930a574c
  20:        0x10b8d286c - std::rt::lang_start::{{closure}}::h84d60950e46d5210
  21:        0x10b94c891 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hc43f50f6c262e503
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:259:13
  22:        0x10b94c891 - std::panicking::try::do_call::ha2a21b2645967438
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:379:40
  23:        0x10b94c891 - std::panicking::try::h1ca18252e93fb057
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:343:19
  24:        0x10b94c891 - std::panic::catch_unwind::h64441306bfaea78f
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:431:14
  25:        0x10b94c891 - std::rt::lang_start_internal::h37583e1fa93097c4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/rt.rs:34:21
  26:        0x10b8d3919 - _main
```

So looks like there are a few more issues relating to multiple GPU's and Contexts and Queues

**Comment by not-an-aardvark** [comment]
So I ended up making changes to the build setup for unrelated reasons in https://github.com/not-an-aardvark/lucky-commit/commit/000000054b982e65a7e7591ddc3bc11efd72529e. Does the current code on `main` (at 000000054b982e65a7e7591ddc3bc11efd72529e) run as expected for you? (This isn't entirely fixed since it still [only uses the first device](https://github.com/not-an-aardvark/lucky-commit/blob/000000054b982e65a7e7591ddc3bc11efd72529e/src/lib.rs#L294) even when multiple devices are available, but that's an improvement over breaking entirely.)

**Comment by hunter-horton** [comment]
I can confirm that building latest `main` branch properly built and successfully executed on my Macbook Pro. Looking in activity monitor, it appears as though by selecting the first option, it is using the integrated graphics of the intel APU instead of the dedicated graphics. This still drops the benchmark from 27s on the CPU implementation to .03s, so I would say "good enough" haha.

**Comment by not-an-aardvark** [comment]
Sounds good, I'll close this then.
